# Site Settings
name: QML.ai
title: QML.ai | A blog for Quantum Machine Learning
description: QML.ai is a blog for discussing developments in Quantum Machine Learning.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
